[build-system]
requires = ["poetry>=1.0.9,<2.0"]
build-backend = "poetry.masonry.api"

[tool.poetry]
name = "xbotlib"
version = "0.14.1"
description = "XMPP bots for humans"
authors = ["decentral1se <lukewm@riseup.net>"]
maintainers = ["decentral1se <lukewm@riseup.net>"]
license = "GPLv3"
readme = "README.md"
repository = "https://git.autonomic.zone/decentral1se/xbotlib"
keywords = []

[tool.poetry.dependencies]
python = "^3.6"
slixmpp = "^1.6.0"
humanize = "^3.2.0"
redis = "^3.5.3"
Jinja2 = "^2.11.2"
aiohttp = "^3.7.3"

[tool.poetry.dev-dependencies]
black = "^19.10b0"
flake8 = "^3.8.3"
isort = "^5.0.2"

[tool.black]
line-length = 80
target-version = ["py38"]
include = '\.pyi?$'

[tool.isort]
include_trailing_comma = true
known_first_party = "xbotlib"
known_third_party = "pytest"
line_length = 80
multi_line_output = 3
skip = ".tox"

[tool.tox]
legacy_tox_ini = """
[tox]
envlist =
    {py36,py37,py38}
    lint
    sort
    format
    type
skip_missing_interpreters = True
isolated_build = True

[testenv]
deps =
  pytest
  pytest-cov
  pytest-mock
commands = pytest test.py --cov={toxinidir}/xbotlib.py --no-cov-on-fail {posargs}

[testenv:lint]
skipdist = True
deps = flake8
commands = flake8 {posargs:--max-line-length 80} xbotlib.py

[testenv:sort]
skipdist = True
deps = isort
commands = isort {posargs:-c} xbotlib.py

[testenv:format]
skipdist = True
deps = black
commands = black {posargs:--check} xbotlib.py

[testenv:type]
skipdist = True
deps = mypy
commands = mypy {posargs:--ignore-missing-imports} xbotlib.py
"""
