[tool.poetry]
name = "finitefloat"
version = "0.1.1"
license = "MIT"
description = "Finite (non-nan, non-inf) float"
authors = ["Shiri Nekono <gexira.halen.toms@gmail.com>"]
maintainers = ["Shiri Nekono <gexira.halen.toms@gmail.com>"]
readme = "README.md"
homepage = "https://github.com/nekonoshiri/finitefloat"
repository = "https://github.com/nekonoshiri/finitefloat"
documentation = "https://github.com/nekonoshiri/finitefloat"
keywords = ["float"]
classifiers = [
  "Development Status :: 4 - Beta",
  "Intended Audience :: Developers",
  "Topic :: Software Development :: Libraries",
  "Topic :: Utilities"
]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
black = "^20.8b1"
flake8 = "^3.8.4"
invoke = "^1.5.0"
isort = "^5.7.0"
mypy = "^0.800"
pytest = "^6.2.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

