include:
  - project: 'opqa/cicd_templates'
    ref: master
    file: '/templates/.sonarqube_code_check.yml'
  - project: 'opqa/cicd_templates'
    ref: master 
    file: '/templates/.pypi_package.yml'

stages:
  - test
  - sonarqube-check
  - pages
  - private_pypi_package 
  - public_pypi_package 

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  PIP_OPTS: "--index-url https://pypi.tuna.tsinghua.edu.cn/simple"


test-py3:
  before_script:
    - python -V
    - pip install nose $PIP_OPTS
    - pip install -r requirements_dev.txt $PIP_OPTS
  tags:
  - seqflow-tools-bj
  image: python:3.7.5
  stage: test
  script:
    - nosetests -v

test-py2:
  before_script:
    - python -V
    - pip install nose $PIP_OPTS
    - pip install -r requirements_dev.txt $PIP_OPTS
  tags:
  - seqflow-tools-bj
  image: python:2.7
  stage: test
  script:
    - nosetests -v


coverage-py3:
  before_script:
    - python -V
    - pip install nose $PIP_OPTS
    - pip install -r requirements_dev.txt $PIP_OPTS
  tags:
  - seqflow-tools-bj
  image: python:3.7.5
  stage: test
  artifacts:
    paths:
      - cover3
  script:
    - nosetests --with-coverage --cover-branches --cover-erase --cover-package=gwc --cover-html --cover-html-dir=cover3 -v .
  only:
    - master
    - merge_requests

coverage-py2:
  before_script:
    - python -V
    - pip install nose $PIP_OPTS
    - pip install -r requirements_dev.txt $PIP_OPTS
  tags:
  - seqflow-tools-bj
  image: python:2.7
  stage: test
  artifacts:
    paths:
      - cover2
  script:
    - nosetests --with-coverage --cover-branches --cover-erase --cover-package=gwc --cover-html --cover-html-dir=cover2 -v .
  only:
    - master
    - merge_requests

pages:
  image: alpine:3.2
  tags:
    - seqflow-tools-bj
  stage: pages
  script:
    - mkdir public
    - mv cover2 public/cover2
    - mv cover3 public/cover3
    - mv docs/* public/
    - mv README.md public/README.md
    - ls public
  artifacts:
    paths:
      - public/
    expire_in: 30 days
  only:
    - master
    - merge_requests