# The VMs' SSH username, e.g. centos
ssh_user: ''

# The user's password for SSH connection. This cannot be used with ssh_key_path
ssh_password: ''

# Your private SSH key local path used to connect to all VMs
ssh_key_path: ''

# Local path to a valid Cloudify license
cloudify_license_path: ''

# Manager RPM to install on the cluster instances. This can be a download link or a local path.
manager_rpm_path: 'http://repository.cloudifysource.org/cloudify/5.1.1/ga-release/cloudify-manager-install-5.1.1-ga.el7.x86_64.rpm'

# This section is only relevant if using LDAP
ldap:
  # This should include the protocol and port,
  # e.g. ldap://192.0.2.1:389 or ldaps://192.0.2.45:636
  server: ''

  # The domain, e.g. example.local
  domain: ''

  # True if Active Directory will be used as the LDAP authenticator
  is_active_directory: true

  # This must be provided if the server is using ldaps://
  ca_cert: ''

  # Username and password should only be entered if absolutely required
  # by the ldap service.
  username: ''
  password: ''

  # Any extra LDAP information (separated by the `;` sign. e.g. a=1;b=2)
  dn_extra: ''


# If specified, all the VMs certificates will need to be specified as well
ca_cert_path: ''

# If using a load-balancer, please provide its IP.
# This IP will be written to the manager config.yaml files under
# networks[load_balancer].
# Remark: The load balancer is not installed during the cluster installation.
load_balancer_ip: ''


existing_vms:
    manager-1:
      private_ip: ''
      public_ip: ''  # If not specified, will default to the private-ip
      hostname: ''   # Optional. As specified in the certificate (if specified)
      cert_path: ''  # Need to be supplied if ca_cert_path was supplied
      key_path: ''  # Need to be supplied if ca_cert_path was supplied
      config_path: '' # Optional. In case you wish to use your own config.yaml for this instance.

    manager-2:
      private_ip: ''
      public_ip: ''  # If not specified, will default to the private-ip
      hostname: ''   # Optional. As specified in the certificate (if specified)
      cert_path: ''  # Need to be supplied if ca_cert_path was supplied
      key_path: ''  # Need to be supplied if ca_cert_path was supplied
      config_path: '' # Optional. In case you wish to use your own config.yaml for this instance.

    manager-3:
      private_ip: ''
      public_ip: ''  # If not specified, will default to the private-ip
      hostname: ''   # Optional. As specified in the certificate (if specified)
      cert_path: ''  # Need to be supplied if ca_cert_path was supplied
      key_path: ''  # Need to be supplied if ca_cert_path was supplied
      config_path: '' # Optional. In case you wish to use your own config.yaml for this instance.

    rabbitmq-1:
      private_ip: ''
      public_ip: ''  # If not specified, will default to the private-ip
      hostname: ''   # Optional. As specified in the certificate (if specified)
      cert_path: ''  # Need to be supplied if ca_cert_path was supplied
      key_path: ''  # Need to be supplied if ca_cert_path was supplied
      config_path: '' # Optional. In case you wish to use your own config.yaml for this instance.

    rabbitmq-2:
      private_ip: ''
      public_ip: ''  # If not specified, will default to the private-ip
      hostname: ''   # Optional. As specified in the certificate (if specified)
      cert_path: ''  # Need to be supplied if ca_cert_path was supplied
      key_path: ''  # Need to be supplied if ca_cert_path was supplied
      config_path: '' # Optional. In case you wish to use your own config.yaml for this instance.

    rabbitmq-3:
      private_ip: ''
      public_ip: ''  # If not specified, will default to the private-ip
      hostname: ''   # Optional. As specified in the certificate (if specified)
      cert_path: ''  # Need to be supplied if ca_cert_path was supplied
      key_path: ''  # Need to be supplied if ca_cert_path was supplied
      config_path: '' # Optional. In case you wish to use your own config.yaml for this instance.


external_db_configuration:
  host: '' # The external DB host name (or IP address)
  ca_path: '' # The external DB CA certificate

  # If your database is an Azure DBaaS instance, you must set 'server_username'
  # so it includes the database name as a suffix. For example, if your database
  # name is "mycfydb" and your username is "test", then "server_username"
  # should be "mycfydb@test".
  server_db_name: ''  # master db name
  server_username: ''  # master username to login external database
  server_password: ''  # password of master username to login external database

  # The following apply if your database is an Azure DBaaS instance:
  #
  #   * "cloudify_username" must include the database name as a suffix. For example,
  #     if your desired database username is "cloudify" and your database name is
  #     "test", then "cloudify_username" should be "cloudify@test".
  #
  #   * "cloudify_username" must be different from "server_username".
  cloudify_db_name: cloudify_db
  cloudify_username: cloudify
  cloudify_password: ''


# If the credentials are not specified, random self-generated ones will be used and written to {{ credentials_file_path }}
credentials:
  manager:
    admin_username: 'admin'
    admin_password: ''

  rabbitmq:
    username: ''
    password: ''
    erlang_cookie: ''

  prometheus:
    username: ''
    password: ''
